services:

  market:
    image: billing-experiment:0.0.1
    ports:
      - 5555:5555
    command: python3 launch.py market market 5555 market
    networks:
      - experiment

  billing:
    image: billing-experiment:0.0.1
    ports:
      - 5554:5554
    command: python3 launch.py bill market 5555 billing
    networks:
      - experiment
    depends_on:
      - "market"

  peer0:
    image: billing-experiment:0.0.1
    ports:
      - 5560:5560
    command: python3 launch.py peer market 5555 peer0 5560
    networks:
      - experiment
    depends_on:
      - "market"

  peer1:
    image: billing-experiment:0.0.1
    ports:
      - 5561:5561
    command: python3 launch.py peer market 5555 peer1 5561
    networks:
      - experiment
    depends_on:
      - "market"

  peer2:
    image: billing-experiment:0.0.1
    ports:
      - 5562:5562
    command: python3 launch.py peer market 5555 peer2 5562
    networks:
      - experiment
    depends_on:
      - "market"

  peer3:
    image: billing-experiment:0.0.1
    ports:
      - 5563:5563
    command: python3 launch.py peer market 5555 peer3 5563
    networks:
      - experiment
    depends_on:
      - "market"

  peer4:
    image: billing-experiment:0.0.1
    ports:
      - 5564:5564
    command: python3 launch.py peer market 5555 peer4 5564
    networks:
      - experiment
    depends_on:
      - "market"

networks:
  experiment:
    name: "experiment"
    driver: bridge